/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author elisc
 */
public class AccountGUI extends javax.swing.JFrame {

    /**
     * Creates new form KontoGUI
     */
    public AccountGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pumLog = new javax.swing.JPopupMenu();
        pumLogMenu = new javax.swing.JMenu();
        pumLogMenuAddAccount = new javax.swing.JMenuItem();
        pumUser = new javax.swing.JPopupMenu();
        pumUserMenu = new javax.swing.JMenu();
        pumUserMenuAddUser = new javax.swing.JMenuItem();
        pumUserMenuAccountTest = new javax.swing.JMenuItem();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        ltUser = new javax.swing.JList<>();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        lbAccount = new javax.swing.JLabel();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        taLog = new javax.swing.JTextArea();

        pumLogMenu.setText("jMenu1");

        pumLogMenuAddAccount.setText("jMenuItem1");
        pumLogMenuAddAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pumLogMenuAddAccountActionPerformed(evt);
            }
        });
        pumLogMenu.add(pumLogMenuAddAccount);

        pumLog.add(pumLogMenu);

        pumUserMenu.setText("jMenu1");

        pumUserMenuAddUser.setText("jMenuItem1");
        pumUserMenuAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pumUserMenuAddUserActionPerformed(evt);
            }
        });
        pumUserMenu.add(pumUserMenuAddUser);

        pumUserMenuAccountTest.setText("jMenuItem1");
        pumUserMenuAccountTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pumUserMenuAccountTestActionPerformed(evt);
            }
        });
        pumUserMenu.add(pumUserMenuAccountTest);

        pumUser.add(pumUserMenu);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("User");
        jInternalFrame1.setVisible(true);

        ltUser.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ltUser);

        jInternalFrame1.getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jInternalFrame2.setTitle("Account");
        jInternalFrame2.setVisible(true);
        jInternalFrame2.getContentPane().add(lbAccount, java.awt.BorderLayout.CENTER);

        jInternalFrame3.setTitle("Log-output");
        jInternalFrame3.setVisible(true);

        taLog.setColumns(20);
        taLog.setRows(5);
        taLog.setComponentPopupMenu(pumLog);
        jScrollPane2.setViewportView(taLog);

        jInternalFrame3.getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInternalFrame3, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
            .addComponent(jInternalFrame2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(jInternalFrame3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pumLogMenuAddAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pumLogMenuAddAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pumLogMenuAddAccountActionPerformed

    private void pumUserMenuAccountTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pumUserMenuAccountTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pumUserMenuAccountTestActionPerformed

    private void pumUserMenuAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pumUserMenuAddUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pumUserMenuAddUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAccount;
    private javax.swing.JList<String> ltUser;
    private javax.swing.JPopupMenu pumLog;
    private javax.swing.JMenu pumLogMenu;
    private javax.swing.JMenuItem pumLogMenuAddAccount;
    private javax.swing.JPopupMenu pumUser;
    private javax.swing.JMenu pumUserMenu;
    private javax.swing.JMenuItem pumUserMenuAccountTest;
    private javax.swing.JMenuItem pumUserMenuAddUser;
    private javax.swing.JTextArea taLog;
    // End of variables declaration//GEN-END:variables
}
